# We use C because conda manages our Python version
language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed but can no longer be installed with
# sudo apt-get.
addons:
    apt:
        packages:
            - libatlas-dev
            - liblapack-dev
            - gfortran
            - graphviz
            - texlive-latex-extra
            - dvipng

# Configure the build environment. Global varibles are defined for all configurations.
env:
    global:
        - PREVIOUS_NUMPY=1.10.4
        - PYTHON_VERSION=2.7
        - TEST_MODE='offline'
        - NUMPY_VERSION='stable'
        - ASTROPY_VERSION='stable'
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='astropy astropy-ci-extras conda-forge'
        - CONDA_DEPENDENCIES='openjpeg Cython jinja2 scipy matplotlib requests beautifulsoup4 sqlalchemy scikit-image pytest wcsaxes pyyaml pandas nomkl pytest-cov coverage'
        - PIP_DEPENDENCIES='suds-jurko sphinx-gallery glymur'

    matrix:
        - PYTHON_VERSION=3.4 SETUP_CMD='test' DEBUG=True
        - PYTHON_VERSION=3.5 SETUP_CMD='test' DEBUG=True

install:
    - git clone -b test git://github.com/bsipocz/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - source continuous-integration/travis/openjpeg.sh  # so glymur knows where to look

before_script:
    # Download the sample data for the build of the documentation.
    - if [[ $SETUP_CMD == *sphinx* ]]; then python -c "import sunpy.data; sunpy.data.download_sample_data()"; fi
    - if [[ $SETUP_CMD == *figure* ]]; then conda env create --file sunpy/tests/figure_tests_env_$PYTHON_VERSION.yml; source activate sunpy-figure-tests; fi

script:
    - $MAIN_CMD $SETUP_CMD

# after_success:
#     - if [[ $SETUP_CMD == *coverage* ]]; then coveralls --rcfile='./sunpy/tests/coveragerc'; fi

# Notify the IRC channel of build status
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d1bf84e1bc1293e4dbc5
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MENhZGFpciUzQW1hdHJpeC5vcmcvJTIxTWVSZEZwRW9uTG9Dd2hvSGVUJTNBbWF0cml4Lm9yZw"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
